# Changes here will be overwritten by Copier
_commit: c124449
_src_path: https://github.com/python-project-templates/base.git
add_docs: false
add_extension: python
add_wiki: false
email: t.paine154@gmail.com
github: airflow-laminar
project_description: Pydantic models for Apache Airflow
project_name: pydantic-airflow
python_version_primary: '3.11'
team: the pydantic-airflow authors
